"""Russian display labels for dataset codes, used by the web API."""

STATUS_LABELS = {
    "completed": "Завершено",
    "in_progress": "В процессе",
    "dropped": "Прекращено",
    "no_show": "Пропуск",
    "declined": "Отказ",
    "overdue": "Просрочено",
}

FORMAT_LABELS = {"online": "Онлайн", "offline": "Очно", "self_paced": "В своём темпе"}

LEVEL_LABELS = {
    0: "Ещё не знаком",
    1: "Знаю основы",
    2: "Решаю типовые задачи с поддержкой",
    3: "Работаю самостоятельно",
    4: "Решаю сложные задачи и помогаю другим",
    5: "Задаю стандарты",
}

ROLE_LABELS = {
    "Backend Engineer": "Разработчик серверной части",
    "Frontend Engineer": "Разработчик интерфейсов",
    "Data Analyst": "Аналитик данных",
    "QA Engineer": "Инженер по качеству",
    "Product Manager": "Менеджер продукта",
    "HR Business Partner": "HR-партнёр",
    "Sales Manager": "Менеджер по продажам",
    "Customer Support Specialist": "Специалист поддержки",
}

GRADE_LABELS = {
    "Junior": "Начинающий",
    "Middle": "Самостоятельный специалист",
    "Senior": "Старший специалист",
    "Lead": "Ведущий специалист",
}

SKILL_LABELS = {
    "Python": "Программирование на Python",
    "Java": "Программирование на Java",
    "SQL": "Запросы к данным (SQL)",
    "API Design": "Проектирование API",
    "System Design": "Проектирование систем",
    "Cloud Platforms": "Облачные платформы",
    "Containers & Orchestration": "Контейнеры и управление ими",
    "CI/CD": "Автоматизация сборки и выпуска",
    "Application Security": "Безопасность приложений",
    "Observability": "Мониторинг работы систем",
    "JavaScript": "Программирование на JavaScript",
    "TypeScript": "Программирование на TypeScript",
    "React": "Интерфейсы на React",
    "HTML & CSS": "Вёрстка страниц",
    "Web Performance": "Быстродействие сайтов",
    "Web Accessibility": "Доступность интерфейсов",
    "Test Design": "Проектирование тестов",
    "Test Automation": "Автоматизация тестирования",
    "API Testing": "Тестирование API",
    "Load Testing": "Нагрузочное тестирование",
    "Statistics": "Статистика",
    "A/B Testing": "A/B-тестирование",
    "Data Visualization": "Визуализация данных",
    "BI Tools": "Инструменты бизнес-аналитики",
    "Data Modeling": "Моделирование данных",
    "Machine Learning Fundamentals": "Основы машинного обучения",
    "Product Discovery": "Поиск потребностей пользователей",
    "Roadmapping & Prioritization": "Планирование и приоритеты",
    "Product Analytics": "Продуктовая аналитика",
    "UX Research": "Исследование опыта пользователей",
    "Requirements Writing": "Описание требований",
    "Agile Practices": "Гибкие методы работы",
    "Project Management": "Управление проектами",
    "Talent Acquisition": "Подбор сотрудников",
    "Employee Relations": "Взаимоотношения с сотрудниками",
    "Labor Law": "Трудовое право",
    "HR Analytics": "HR-аналитика",
    "Learning Program Design": "Разработка учебных программ",
    "Compensation & Benefits": "Оплата труда и льготы",
    "Prospecting": "Поиск клиентов",
    "Negotiation": "Переговоры",
    "CRM Systems": "Системы работы с клиентами (CRM)",
    "Account Management": "Развитие отношений с клиентами",
    "Product Knowledge": "Знание продукта",
    "Customer Service": "Клиентский сервис",
    "Technical Troubleshooting": "Решение технических проблем",
    "Communication": "Общение",
    "Public Speaking": "Публичные выступления",
    "Written Communication": "Письменное общение",
    "Stakeholder Management": "Работа с заинтересованными сторонами",
    "Leadership": "Лидерство",
    "Mentoring": "Наставничество",
    "Feedback": "Обратная связь",
    "Conflict Resolution": "Разрешение конфликтов",
    "Teamwork": "Командная работа",
    "Emotional Intelligence": "Эмоциональный интеллект",
    "Problem Solving": "Решение проблем",
    "Critical Thinking": "Критическое мышление",
    "Time Management": "Управление временем",
    "Adaptability": "Адаптивность",
}

EVENT_LABELS = {
    "Information Security Awareness": "Информационная безопасность",
    "Personal Data Protection": "Защита персональных данных",
    "Code of Conduct & Workplace Safety": "Кодекс поведения и безопасность труда",
    "New Employee Onboarding": "Знакомство с компанией",
    "System Design Fundamentals": "Основы проектирования систем",
    "Designing High-Load Systems": "Проектирование высоконагруженных систем",
    "Architecture Review Circle": "Клуб разбора архитектуры",
    "Business Writing & Documentation": "Деловая переписка и документация",
    "Cloud Certification Prep": "Подготовка к сертификации по облачным технологиям",
    "Kubernetes in Practice": "Kubernetes на практике",
    "Secure Coding Workshop": "Практикум по безопасной разработке",
    "Advanced Python": "Продвинутый Python",
    "TypeScript in Depth": "Углублённый TypeScript",
    "Web Performance Deep Dive": "Углублённая оптимизация сайтов",
    "Web Performance Fundamentals": "Основы быстродействия сайтов",
    "Accessible Interfaces": "Доступные интерфейсы",
    "React Patterns & State Management": "Подходы к разработке на React и управление состоянием",
    "Test Automation Bootcamp": "Интенсив по автоматизации тестирования",
    "API & Performance Testing Workshop": "Практикум по API и нагрузочному тестированию",
    "Applied Statistics for Analysts": "Прикладная статистика для аналитиков",
    "A/B Testing Workshop": "Практикум по A/B-тестированию",
    "SQL & BI for Analytics": "SQL и бизнес-аналитика",
    "Data Storytelling & Visualization": "Как рассказывать истории с помощью данных",
    "Machine Learning for Analysts": "Машинное обучение для аналитиков",
    "Dimensional Data Modeling": "Многомерное моделирование данных",
    "Product Discovery Lab": "Лаборатория исследования потребностей пользователей",
    "Roadmapping & Agile Planning": "Планирование продукта и гибкие методы работы",
    "Labor Law & Employee Relations": "Трудовое право и отношения с сотрудниками",
    "People Analytics & Total Rewards": "HR-аналитика и система вознаграждений",
    "Structured Interviewing": "Структурированные собеседования",
    "Designing Learning Programs": "Разработка учебных программ",
    "Negotiation Masterclass": "Мастер-класс по переговорам",
    "Consultative Selling & Prospecting": "Консультативные продажи и поиск клиентов",
    "Handling Difficult Conversations": "Как вести сложные разговоры",
    "Technical Troubleshooting Academy": "Решение технических проблем",
    "Public Speaking Club": "Клуб публичных выступлений",
    "Mentor Track": "Программа наставничества",
    "Leadership Foundations": "Основы лидерства",
    "Time & Priority Management": "Управление временем и приоритетами",
    "Structured Problem Solving": "Системный подход к решению проблем",
}

FACTOR_LABELS = {
    "critical_gap": "Развивает навык, обязательный для карьерной цели.",
    "required_gap": "Сокращает расстояние до нужного уровня навыков.",
    "grade_fit": "Подходит вашему текущему профессиональному уровню.",
    "target_alignment": "Подходит роли и уровню вашей карьерной цели.",
    "goal_alignment": "Связан с указанной вами карьерной целью.",
    "history_avoidance": "Похожие занятия вы ранее пропускали, отклоняли или не завершали — это снижает приоритет.",
    "engagement": "Учтён ваш опыт завершения похожих занятий.",
    "feedback": "Учтены ваши оценки похожих занятий.",
    "availability": "Учтено, когда можно начать занятие.",
    "duration": "Учтено время на занятие: длительные активности получают меньший приоритет.",
}

# Third-person wording for HR, who looks at someone else's profile.
FACTOR_LABELS_NEUTRAL = {
    "critical_gap": "Развивает навык, обязательный для карьерной цели.",
    "required_gap": "Сокращает расстояние до нужного уровня навыков.",
    "grade_fit": "Подходит текущему профессиональному уровню сотрудника.",
    "target_alignment": "Подходит роли и уровню карьерной цели сотрудника.",
    "goal_alignment": "Связан с карьерной целью, которую указал сотрудник.",
    "history_avoidance": "Похожие занятия сотрудник ранее пропускал, отклонял или не завершал — это снижает приоритет.",
    "engagement": "Учтён опыт сотрудника в похожих занятиях.",
    "feedback": "Учтены оценки, которые сотрудник ставил похожим занятиям.",
    "availability": "Учтено, когда можно начать занятие.",
    "duration": "Учтено время на занятие: длительные активности получают меньший приоритет.",
}

BADGE_LABELS = {
    "first_step": ("🌱", "Первый шаг", "Завершена первая добровольная активность"),
    "self_starter": ("🚀", "По своей инициативе", "Активность выбрана самостоятельно"),
    "comeback": ("🔁", "Возвращение", "Возвращение к навыку, который раньше не получилось развить"),
    "grown_since_review": ("📈", "Рост после оценки", "Навыки выросли после последней оценки"),
    "critical_closed": ("🎯", "Ключевой навык", "Обязательный навык цели на нужном уровне"),
    "halfway": ("⛰️", "Полпути", "Покрыта половина требований цели"),
    "ready": ("🏆", "Готов к цели", "Все обязательные навыки цели на нужном уровне"),
}
